### ISSUE TITLE
python3 compat?

### ISSUE THREAD

**Issue by cyrinux** [DefectDojo/defectdojo_api#28]
Hi,

I got this running example, after adding () to print() in dojo_populate.py, i got this one.
```
» ❯ python3 dojo_populate.py
Traceback (most recent call last):
  File "dojo_populate.py", line 27, in <module>
    dd = defectdojo.DefectDojoAPI(host, api_key, user, debug=False)
  File "/home/cyril/trydefectdojoapi/venv/lib/python3.7/site-packages/defectdojo_api/defectdojo.py", line 37, in __init__
    if host.split('/') > 3:
TypeError: '>' not supported between instances of 'list' and 'int'
```
Thanks for help

**Comment by Martin2877** [comment]
I have the same problem.

**Comment by damiencarol** [comment]
seems an error in one of the scripts.
@Martin2877 @cyrinux  The code your referring to was modified by @aaronweaver on Aug 14, 2018
=> https://github.com/DefectDojo/defectdojo_api/commit/0eab5e58028f4a9044af6a06c06985a37b243248#diff-398ee4538a05ce9f45dc774f83e67aa783e808ab48aa91ad9ec26ce22bd2fb26

**Comment by jyotiraws** [comment]
i have the same problem but using defectdojo_api==1.1.3 helped

**Comment by benmeyer50** [comment]
Any updates on this?

**Comment by Siryu6** [comment]
You can quickfix it in ste-packages/defectdojo_api/defectdojo.py
Replace:
`if host.split('/') > 3:`
By:
`if len(host.split('/')) > 3:`

I'll make a PR for it

**Comment by damiencarol** [comment]
FYI: this piece of code was removed in https://github.com/DefectDojo/defectdojo_api/commit/0eab5e58028f4a9044af6a06c06985a37b243248#diff-398ee4538a05ce9f45dc774f83e67aa783e808ab48aa91ad9ec26ce22bd2fb26.
Should it be more simple to update the module to a new version?
